config/routes.rb
Rails.application.routes.draw do
  root to: "janken#rock"
  namespace :janken do
    get :rock
    get :scissors
    get :paper
  end

  resources :random_janken, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/janken_controller.rb
class JankenController < ApplicationController
  layout "janken"
end

app/controllers/random_janken_controller.rb
class RandomJankenController < ApplicationController
  layout "random_janken"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/janken/paper.html.erb
<div>
  <%= link_to janken_rock_path do %>
    <%= image_tag "paper.gif" %>
  <% end %>
</div>

app/views/janken/rock.html.erb
<div>
  <%= link_to janken_scissors_path do %>
    <%= image_tag "rock.gif" %>
  <% end %>
</div>

app/views/janken/scissors.html.erb
<div>
  <%= link_to janken_paper_path do %>
    <%= image_tag "scissors.gif" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewUniversalDesignJanken</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/janken.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewUniversalDesignJanken</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'janken', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/random_janken.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewUniversalDesignJanken</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'random_janken', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/random_janken/index.html.erb
<div class="roulette" style="display:none;">
  <%= image_tag "rock.gif" %>
  <%= image_tag "scissors.gif" %>
  <%= image_tag "paper.gif" %>
</div>